### PR TITLE
fix receiver selection to avoid panics

### LINKED ISSUE #7: tokio select pre-conditions not stopping a panic
The `select!` pre-conditions in e.g. https://github.com/penumbra-zone/tower-abci/blob/main/src/buffer4/worker.rs#L156 that check that a receiver is `Some` don't work as expected.

Excerpt from [tokio's docs](https://docs.rs/tokio/1.13.0/tokio/macro.select.html):
1. Evaluate all provided <precondition> expressions. If the precondition returns false, disable the branch for the remainder of the current call to select!. Re-entering select! due to a loop clears the “disabled” state.
2. Aggregate the <async expression>s from each branch, including the disabled ones. If the branch is disabled, <async expression> is still evaluated, but the resulting future is not polled.

So even if the pre-condition is `false`, the expressions are still evaluated and hence panic on the unwrap, e.g.:
```
Location: /usr/local/rust/cargo/git/checkouts/tower-abci-0d01b039e0b7a0c9/d63c0d0/src/buffer4/worker.rs:156
Message: called `Option::unwrap()` on a `None` value
The application panicked (crashed).
```

### PR DESCRIPTION
**Pull request by tzemanovic**
closes #7

### CODE REVIEW

File: src/buffer4/worker.rs [hunk 1]
```diff
@@ -225,3 +226,11 @@ impl Handle {
...
     }
 }
+
+async fn option_and_then<T, U, F, Fut>(x: Option<T>, f: F) -> Option<U>
+where
+    F: FnOnce(T) -> Fut,
+    Fut: Future<Output = Option<U>>,
+{
+    f(x?).await
+}
```
Comment (hawkw) [inline src/buffer4/worker.rs:236]: this is specifically used for calling `recv`, so I think it isn't _really_ necessary to take closure. it could just be:
```suggestion
async fn recv_option<T>(x: Option<&mut mpsc::Receiver<Option<T>>>)) -> Option<T> {
    x?.recv().await
}
```

File: src/buffer4/worker.rs [hunk 2]
```diff
@@ -153,7 +154,7 @@ where
                 // Using a biased select means the channels will be polled
                 // in priority order, not in a random (fair) order.
                 biased;
-                msg = self.rx1.as_mut().unwrap().recv(), if self.rx1.is_some() => {
+                msg = option_and_then(self.rx1.as_mut(), |rx| rx.recv()) => {
```
Comment (hawkw) [inline src/buffer4/worker.rs:157]: if you apply my suggestion from below, this could be simplified to remove the closure:
```suggestion
                msg = recv_option(self.rx1.as_mut()) => {
```

File: src/buffer4/worker.rs [hunk 3]
```diff
@@ -162,7 +163,7 @@ where
                         None => self.rx1 = None,
                     }
                 }
-                msg = self.rx2.as_mut().unwrap().recv(), if self.rx2.is_some() => {
+                msg = option_and_then(self.rx2.as_mut(), |rx| rx.recv()) => {
```
Comment (hawkw) [inline src/buffer4/worker.rs:166]:
```suggestion
                msg = recv_option(self.rx2.as_mut()) => {
```

File: src/buffer4/worker.rs [hunk 4]
```diff
@@ -171,7 +172,7 @@ where
                         None => self.rx2 = None,
                     }
                 }
-                msg = self.rx3.as_mut().unwrap().recv(), if self.rx2.is_some() => {
+                msg = option_and_then(self.rx3.as_mut(), |rx| rx.recv()) => {
```
Comment (hawkw) [inline src/buffer4/worker.rs:175]:
```suggestion
                msg = recv_option(self.rx3.as_mut()) => {
```

File: src/buffer4/worker.rs [hunk 5]
```diff
@@ -180,7 +181,7 @@ where
                         None => self.rx3 = None,
                     }
                 }
-                msg = self.rx4.as_mut().unwrap().recv(), if self.rx2.is_some() => {
+                msg = option_and_then(self.rx4.as_mut(), |rx| rx.recv()) => {
```
Comment (hawkw) [inline src/buffer4/worker.rs:184]:
```suggestion
                msg = recv_option(self.rx4.as_mut()) => {
```

File: src/buffer4/worker.rs [hunk 6]
```diff
@@ -3,6 +3,7 @@ use super::{
     message::Message,
 };
 use futures::stream::StreamExt;
+use std::future::Future;
```
Comment (hawkw) [inline src/buffer4/worker.rs:6]: i think that if we apply my suggestion on `option_and_then` below, we wouldn't need to import the `Future` trait 
```suggestion
```

**Review by hawkw — APPROVED** [review]
This looks like a good solution to me! I had one suggestion on how we could potentially make the code a bit simpler, take it or leave it!

**Comment by hdevalence** [comment]
Happy to merge this with or without @hawkw 's suggestion!

**Comment by tzemanovic** [comment]
Thanks @hawkw. I agree, simple is better

File: src/buffer4/worker.rs [hunk 7]
```diff
@@ -225,3 +225,7 @@ impl Handle {
             .unwrap_or_else(|| Closed::new().into())
     }
 }
+
+async fn recv_option<T>(x: Option<&mut mpsc::Receiver<Option<T>>>)) -> Option<T> {
```
Comment (tzemanovic) [inline src/buffer4/worker.rs:229]: woops, didn't notice
```suggestion
async fn recv_option<T>(x: Option<&mut mpsc::Receiver<Option<T>>>) -> Option<T> {
```

File: src/buffer4/worker.rs [hunk 8]
```diff
@@ -225,3 +225,7 @@ impl Handle {
             .unwrap_or_else(|| Closed::new().into())
     }
 }
+
+async fn recv_option<T>(x: Option<&mut mpsc::Receiver<Option<T>>>) -> Option<T> {
```
Comment (tzemanovic) [inline src/buffer4/worker.rs:229]: ah, this should be
```suggestion
async fn recv_option<T>(x: Option<&mut mpsc::UnboundedReceiver<T>>) -> Option<T> {
```
